//									Voce Menù												Nome Utente						Nome Lista	
	
var tweetQuery = {	"Photography News"					:		["140photography", 			"news"],
										"Photography Agencies"			:		["140photography", 			"agencies"],
										"Photography Associations"	:		["140photography", 			"associations"],
										"Photography Contests"			:		["140photography", 			"international-contests"],
										"Photo Editors"							:		["140photography", 			"photo-editors"],
										"Photography Magazines"			:		["140photography", 			"magazines"],
										"Photography Schools"				:		["140photography", 			"photography-schools"],
										"Creative Networks"		 			:		["140photography",			"creative-networks"],
										"Photojournalism"						:		["140photography", 			"photojournalism"],
										"Photographers"							: 	["140photography", 			"photographers"],
										"Fashion Photography"				:		["140photography", 			"fashion"],
										"Model Agencies"						:		["140photography", 			"models"],
										"Make Up & Styling"					:		["140photography", 			"make-up"],
										"DSLR Video"								:		["140photography", 			"dslr-video"],
										"Iphonegraphy"							:		["140photography", 			"iphonegraphy"],
										"Equipment, Brands & Dealers":	["140photography", 			"brands-dealers"],
										"Photography Tips & Tutorials":	["140photography", 			"tips-tutorials"],
										"Postproduction"						:		["140photography", 			"postproduction"],
										"Museums & Exhibitions"			:		["140photography", 			"exhibitions-museums"],
										"World Organizations"				:		["140photography", 			"world-organizations"],
				 					};