// Generated by CoffeeScript 1.4.0
var loadTweets;

loadTweets = function(title, div, users, list, n) {
  $("#deck").html("<h1>" + title + "</h1>");
  $("#deck").append("<div id=\"tweetFeed\"></div>");
  $(div).html("");
  return $(div).jTweetsAnywhere({
    username: users,
    list: list,
    count: n,
    showTweetFeed: {
      showProfileImages: true,
      showUserScreenNames: true,
      showUserFullNames: true,
      showActionReply: true,
      showActionRetweet: true,
      showActionFavorite: true,
      autorefresh: {
        mode: "trigger-insert",
        interval: 300
      },
      paging: {
        mode: "more"
      },
      showTimestamp: {
        refreshInterval: 60
      }
    }
  });
};

$(function() {
  var e, hash;
  hash = window.location.hash.slice(1);
  loadTweets('Photography News', '#tweetFeed', tweetQuery["Photography News"][0], tweetQuery["Photography News"][1], 15);
  for (e in tweetQuery) {
    $("#menu ul").append("<li id=\"" + e + "\"><a href=\"#\" >" + e + "</a></li>");
    $("#menu-mobile select").append("<option id=\"" + e + "\"><a href=\"#\" >" + e + "</a></option>");
    $("#menu li").first().addClass("active");
  }
  $("#menu li").click(function() {
    $("#menu li").removeClass("active");
    $(this).addClass("active");
    $("#menu-mobile select").val($(this).attr("id"));
    return loadTweets($(this).attr("id"), "#tweetFeed", tweetQuery[$(this).attr("id")][0], tweetQuery[$(this).attr("id")][1], 15);
  });
  return $("#menu-mobile select").change(function() {
    return loadTweets($(this).val(), "#tweetFeed", tweetQuery[$(this).val()][0], tweetQuery[$(this).val()][1], 15);
  });
});
